import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    {type: 'autogenerated', dirName: '.'},
    {
      type: 'category',
      label: 'ROS 2 Fundamentals',
      link: {
        type: 'doc',
        id: 'ros2-fundamentals/chapter-1-ros2-fundamentals',
      },
      items: [
        'ros2-fundamentals/chapter-1-ros2-fundamentals',
        'ros2-fundamentals/chapter-2-python-control',
        'ros2-fundamentals/chapter-3-urdf-fundamentals',
        {
          type: 'category',
          label: 'Exercises',
          items: [
            'ros2-fundamentals/exercises/chapter-1-exercises',
            'ros2-fundamentals/exercises/chapter-2-exercises',
            'ros2-fundamentals/exercises/chapter-3-exercises'
          ]
        }
      ],
    },
    {
      type: 'category',
      label: 'Digital Twin (Gazebo & Unity)',
      link: {
        type: 'doc',
        id: 'digital-twin/chapter-1-physics-simulation',
      },
      items: [
        'digital-twin/chapter-1-physics-simulation',
        'digital-twin/chapter-2-sensor-simulation',
        'digital-twin/chapter-3-unity-integration',
        'digital-twin/summary',
        {
          type: 'category',
          label: 'Exercises',
          items: [
            'digital-twin/exercises/chapter-1-exercises',
            'digital-twin/exercises/chapter-2-exercises',
            'digital-twin/exercises/chapter-3-exercises'
          ]
        }
      ],
    },
    {
      type: 'category',
      label: 'Isaac AI Brain (NVIDIA Isaac™)',
      link: {
        type: 'doc',
        id: 'isaac-ai-brain/chapter-1-isaac-sim',
      },
      items: [
        'isaac-ai-brain/chapter-1-isaac-sim',
        'isaac-ai-brain/chapter-2-isaac-ros',
        'isaac-ai-brain/chapter-3-nav2-navigation',
        'isaac-ai-brain/summary',
        {
          type: 'category',
          label: 'Exercises',
          items: [
            'isaac-ai-brain/exercises/chapter-1-exercises',
            'isaac-ai-brain/exercises/chapter-2-exercises',
            'isaac-ai-brain/exercises/chapter-3-exercises'
          ]
        }
      ],
    },
    {
      type: 'category',
      label: 'VLA Robotics (Vision-Language-Action)',
      link: {
        type: 'doc',
        id: 'vla-robotics/chapter-1-voice-to-action',
      },
      items: [
        'vla-robotics/chapter-1-voice-to-action',
        'vla-robotics/chapter-2-llm-cognitive-planning',
        'vla-robotics/chapter-3-autonomous-humanoid',
        'vla-robotics/summary',
        {
          type: 'category',
          label: 'Exercises',
          items: [
            'vla-robotics/exercises/chapter-1-exercises',
            'vla-robotics/exercises/chapter-2-exercises',
            'vla-robotics/exercises/chapter-3-exercises'
          ]
        }
      ],
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
